"""Turn the version-pinned lock into a hash-pinned file for ``pip --require-hashes``.

The deploy host installs dependencies as an administrator, so a substituted
artifact would execute with administrator rights. Version pins alone cannot
detect that; hashes can. This script collects the published SHA256 of every
distribution file (all platforms, wheels and sdists) for each pinned version
from the package index, so one file covers every host we deploy to.

Regenerate after any change to requirements.lock.txt:

    python scripts/pin_lock_hashes.py --out requirements.lock.hashes.txt
    python scripts/pin_lock_hashes.py --check        # verify it is in sync
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from urllib.error import HTTPError, URLError
from urllib.request import urlopen

ROOT = Path(__file__).resolve().parents[1]
LOCK_FILE = ROOT / "requirements.lock.txt"
HASHES_FILE = ROOT / "requirements.lock.hashes.txt"
INDEX_URL = "https://pypi.org/pypi/{name}/{version}/json"
HEADER = [
    "# Generated by scripts/pin_lock_hashes.py - do not edit by hand.",
    "# Install with: pip install --require-hashes -r requirements.lock.hashes.txt",
    "# Hashes cover every published wheel and sdist for the pinned version.",
]
HTTP_TIMEOUT_SECONDS = 30


def pinned_requirements(path: Path) -> list[tuple[str, str]]:
    """Return (name, version) pairs from a version-pinned lock file."""
    pinned: list[tuple[str, str]] = []
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        entry = line.split("\\")[0].split("--hash")[0].strip()
        if "==" not in entry:
            raise ValueError(f"Lock entry is not version-pinned: {line}")
        name, _, version = entry.partition("==")
        pinned.append((name.strip(), version.strip()))
    return pinned


def published_hashes(name: str, version: str) -> list[str]:
    """Return the sorted SHA256 digests published for one pinned release."""
    url = INDEX_URL.format(name=name, version=version)
    try:
        with urlopen(url, timeout=HTTP_TIMEOUT_SECONDS) as response:
            payload = json.load(response)
    except HTTPError as error:
        raise SystemExit(f"Cannot resolve {name}=={version} from the package index: {error}") from None
    except URLError as error:
        raise SystemExit(f"Cannot reach the package index: {error.reason}") from None
    digests = {
        entry["digests"]["sha256"]
        for entry in payload.get("urls", [])
        if isinstance(entry.get("digests", {}).get("sha256"), str)
    }
    if not digests:
        raise SystemExit(f"No published artifacts found for {name}=={version}")
    return sorted(digests)


def recorded_hashes(path: Path) -> dict[str, set[str]]:
    """Return the digests recorded per package name in a hash-pinned file."""
    recorded: dict[str, set[str]] = {}
    current: str | None = None
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("--hash="):
            if current is not None:
                recorded.setdefault(current, set()).add(line.split("sha256:", 1)[-1].strip(" \\"))
            continue
        entry = line.split("\\")[0].split("--hash")[0].strip()
        name = entry.partition("==")[0].strip().lower()
        if name:
            current = name
            recorded.setdefault(name, set())
    return recorded


def verify(path: Path) -> int:
    """Compare the recorded hashes against the index.

    A recorded digest disappearing is a hard failure: upstream never removes a
    published artifact, so it means a yank or a substituted release. A digest the
    index publishes that we have not recorded is only an advisory - pip simply
    refuses that artifact - so it asks for a regeneration rather than failing.
    """
    recorded = recorded_hashes(path)
    problems: list[str] = []
    advisories: list[str] = []
    for name, version in pinned_requirements(LOCK_FILE):
        published = set(published_hashes(name, version))
        expected = recorded.get(name.lower(), set())
        if not expected:
            problems.append(f"{name}=={version}: no hashes recorded")
            continue
        if expected - published:
            problems.append(
                f"{name}=={version}: {len(expected - published)} recorded hash(es) are no longer published"
            )
        if published - expected:
            advisories.append(
                f"{name}=={version}: {len(published - expected)} upstream artifact(s) are not recorded"
            )
    for advisory in advisories:
        print(f"advisory: {advisory}")
    if problems:
        for problem in problems:
            print(f"problem: {problem}", file=sys.stderr)
        return 2
    if advisories:
        print(f"{path.name} still covers every pinned version; re-run without --check to record the new artifacts.")
        return 0
    print(f"{path.name} is in sync with {LOCK_FILE.name}")
    return 0


def render(pinned: list[tuple[str, str]]) -> str:
    lines = list(HEADER)
    for name, version in pinned:
        lines.append(f"{name}=={version} \\")
        digests = published_hashes(name, version)
        for index, digest in enumerate(digests):
            suffix = "" if index == len(digests) - 1 else " \\"
            lines.append(f"    --hash=sha256:{digest}{suffix}")
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", type=Path, default=HASHES_FILE)
    parser.add_argument("--check", action="store_true", help="verify the file is in sync instead of writing it")
    args = parser.parse_args()

    if args.check:
        if not args.out.is_file():
            print(f"{args.out.name} is missing; generate it before deploying.", file=sys.stderr)
            raise SystemExit(2)
        raise SystemExit(verify(args.out))
    args.out.write_text(render(pinned_requirements(LOCK_FILE)), encoding="utf-8")
    print(f"Wrote {args.out}")


if __name__ == "__main__":
    main()
